name: "Build and push"

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: [ "addon-auto-backup", "addon-do-ddns", "addon-s3-sync" ]
        architecture: [ "amd64" ]
        build_from_image: [ "ubuntu-base" ]
        build_from_version: [ "6.1.3" ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: ghcr.io/cristianhenzel/hassio-${{ matrix.addon }}/${{ matrix.architecture }}:latest
          context: ./${{ matrix.addon }}
          file: ./${{ matrix.addon }}/Dockerfile
          cache-from: |
            ghcr.io/cristianhenzel/hassio-${{ matrix.addon }}/${{ matrix.architecture }}:latest
          build-args: |
            BUILD_FROM=ghcr.io/hassio-addons/${{ matrix.build_from_image }}/${{ matrix.architecture }}:${{ matrix.build_from_version }}

      - name: Push
        run: docker push "ghcr.io/cristianhenzel/hassio-${{ matrix.addon }}/${{ matrix.architecture }}:latest"


#    - name: Login to DockerHub
#      uses: docker/login-action@v1
#      with:
#        username: ${{ secrets.DH_USER }}
#        password: ${{ secrets.DH_PAT }}
#    - name: Publish auto-backup
#      uses: home-assistant/builder@master
#      with:
#        args: |
#          --amd64 \
#          --target ${{ matrix.addon }} \
#          --docker-hub ${{ secrets.DH_USER }}
#    - name: Publish do-ddns
#      uses: home-assistant/builder@master
#      with:
#        args: |
#          --amd64 \
#          --target addon-do-ddns \
#          --docker-hub ${{ secrets.DH_USER }}
#    - name: Publish s3-sync
#      uses: home-assistant/builder@master
#      with:
#        args: |
#          --amd64 \
#          --target addon-s3-sync \
#          --docker-hub ${{ secrets.DH_USER }}
