name: "Build and push"

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        addon: [ "addon-auto-backup", "addon-do-ddns", "addon-samba-sync" ]
        architecture: [ "amd64" ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get base image
        id: build_from
        run: echo "::set-output name=build_from::$(jq -r '.build_from.${{ matrix.architecture }}' ${{ matrix.addon }}/build.json)"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          load: true
          tags: ghcr.io/cristianhenzel/hassio-${{ matrix.addon }}/${{ matrix.architecture }}:latest
          context: ./${{ matrix.addon }}
          file: ./${{ matrix.addon }}/Dockerfile
          cache-from: |
            ghcr.io/cristianhenzel/hassio-${{ matrix.addon }}/${{ matrix.architecture }}:latest
          build-args: |
            BUILD_FROM=${{ steps.build_from.outputs.build_from }}

      - name: Push
        run: docker push "ghcr.io/cristianhenzel/hassio-${{ matrix.addon }}/${{ matrix.architecture }}:latest"
